### ISSUE TITLE
data-value not working

### ISSUE THREAD

**Issue by alainlecluse** [Toilal/ng-pickadate#10]
Hi,

I can't wrap my head arround the following: i need to pre fill the feeld with a date (edit of existing data).
Documentation is pointing me to  data-value for this, but i'm not getting it to work.

For example

```
<input  id="input_02"
                class="datepicker"
                name="date"
                type="text"
                autofocuss
                pick-a-date="input_02"
                data-value="2014-06-09"
               pick-a-date-options="{ formatSubmit:'yyyy-mm-dd',format: 'yyyy-mm-dd' }"/>
```

the shown value is empty. but when you click on the input it wil select the correct date.
even more problems arrive when i use ng-model to bind the value. 

Does any body have any clue?

**Comment by alainlecluse** [comment]
It apears that this happens due to the element.pickadate('picker').clear(); in updateValue(newValue);

``` javascript
function updateValue(newValue) {
                if (newValue) {
                    scope.pickADate = (newValue instanceof Date) ? newValue : new Date(newValue);
                    element.pickadate('picker').set('select', scope.pickADate.getTime());
                } else {
                    element.pickadate('picker').clear();
                    scope.pickADate = null;
                }
            }
```

**Comment by Toilal** [comment]
Where is the documentation about `data-value` ? 

The date must be passed to `pick-a-date` directive, instead of "input_02" value. Maybe it could be more clear in README on how to use the directive, but `data-value` simply doesn't exists.

``` html
<input type="text" pick-a-date="curDate"/>
```

Set `curDate` in your controller scope

``` js
$scope.curDate = new Date(2014, 6, 9);
```

**Comment by Toilal** [comment]
ng-model will bind the text value like any other text input, so it's not recommanded to use it along with ng-pickadate.

**Comment by alainlecluse** [comment]
Hi Toilal, thanks for the quick answer. it was not clear from me from the readme. it also refered to http://amsul.ca/pickadate.js/date/#formats "pre-fill values using custom formats or translations" and below.

But your reaction helped a lot.

**Comment by Toilal** [comment]
I'll update README with an example containing JS sources, and i'm also building a small demo app that will be included in sources and published on github webpage.
