### ISSUE TITLE
TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by stef686** [Toilal/ng-pickadate#14]
I've installed this directive as per the documentation however when the page loads I get the following JS errors:

TypeError: Cannot read property 'style' of null
picker.js:7

ReferenceError: Picker is not defined
picker.date.js:5

ReferenceError: Picker is not defined
picker.time.js:5

**Comment by Toilal** [comment]
The ordering of pickadate files is probably wrong. Reopen if you still have this issue.
