### ISSUE TITLE
TypeError: element.pickadate is not a function at /libs/ng-pickadate/ng-pickadate.js:53:17

### ISSUE THREAD

**Issue by nimeetshah0** [Toilal/ng-pickadate#17]
Though I did solve the issue, I figured I will create an entry here for if someone faces the same problem. 
I got this error when trying to use the plugin installed using bower. 

Found that the error was coming from <code>element.pickadate(options);</code>.
I modified it to match the jQuery standards <code>$(element).pickadate(options);</code> and it worked.

Note that I had to modify all <code>element</code> in the file to <code>$(element)</code>.

I'm still not a 100% sure how this fixed the problem. 

Would be nice if someone could shed some light on it.

Thanks

**Comment by Toilal** [comment]
Did you linked jQuery before angular js ? In your index.html,jQuery must be
linked before angularJS in order angularJS to use jQuery instead of jQlite.

**Comment by nimeetshah0** [comment]
Yes, that was the problem. jQuery was linked after angular js. 
Thanks for the input.

**Comment by ziaulrehman40** [comment]
Trying to solve same issue, but above solution didn't work and i have included pickadate after jquery and angular. Any help will be great :)

**Comment by chrisp1001** [comment]
Same thing here. I am using:

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>`

Error: element.pickadate is not a function
.link@http://..../js/ng-picker.js:90:17
bb/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:16:54
ja@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:81:35
m@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:66:274
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:481
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:498
m@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:66:214
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:481
m@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:66:214
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:481
g@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:498
ba/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:58:119
Bc/c/</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:20:497
vf/this.$get</m.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:145:103
vf/this.$get</m.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:145:335
Bc/c/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:20:455
h/<.invoke@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:41:374
Bc/c@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:20:376
Bc@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:21:163
ge@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:19:484
@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:315:135
g/</j@https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:29946
g/</k<@https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:30262

<input class="form-control" name="milestone_finished_until" pick-a-date="milestone_finished_until" type="text">

Any idea?

UPDATE:
Replaced "element.pickadate(" by "$(element).pickadate(" and it works. It seems that I downloaded an old version.
