### ISSUE TITLE
Please add CHANGELOG.md

### ISSUE THREAD

**Issue by simison** [Toilal/ng-pickadate#18]
And thanks for maintaining this! :-)

**Comment by Toilal** [comment]
Sorry, I don't want to maintain this.

**Comment by simison** [comment]
There are easy and quick tools to do this, e.g.: https://www.npmjs.com/package/changelog

**Comment by Toilal** [comment]
I know there are tools, but it requires configuration to add more value than this simple link : https://github.com/Toilal/ng-pickadate/commits/master.

I have few time for this library sorry, I also know CHANGELOG is great for users, but I really don't want to care with this on this repository.

**Comment by simison** [comment]
Fair enough; just remember to follow http://semver.org/ accurately then.
