### ISSUE TITLE
Doesn't work with editable=true

### ISSUE THREAD

**Issue by bluee** [Toilal/ng-pickadate#20]
The directive seems to be not working with Pickadate.js 3.5.6

See sample:
http://plnkr.co/edit/7j2j09

**Comment by theofidry** [comment]
same here

**Comment by Toilal** [comment]
Thanks for reporting ! I'll try to fix.

**Comment by Toilal** [comment]
I've upgraded the demo directory to latest versions for each dependencies, and I can't reproduce the issue from the plnkr. Any idea ? Please try using the demo from this project.

https://rawgit.com/Toilal/ng-pickadate/master/demo/index.html

**Comment by Toilal** [comment]
I can reproduce only when some options are given... If no option is given, it works as expected.

**Comment by Toilal** [comment]
The issue is related to [editable](http://amsul.ca/pickadate.js/date/#editable) option. This option is quite unclear for me, but removing this option makes the plnkr work. It seems it doesn't work either in pickadate.js website.

**Comment by Toilal** [comment]
It's a threading issue in pickadate.js project. https://github.com/amsul/pickadate.js/issues/542
