### ISSUE TITLE
how to get the value in the ng-model ?

### ISSUE THREAD

**Issue by jechazelle** [Toilal/ng-pickadate#22]
Hi !
Thank you for your job.
I have just a question : How to get the value in the ng-model ?

**Comment by jechazelle** [comment]
It's automatic !

**Comment by Toilal** [comment]
Of course, it's just binded with angularJS to your controller's scope :)

**Comment by benjaminrau** [comment]
Hi guys. @Toilal thanks for the great directive. It took me few hours now to watch my scope variable until i figured out that watching date objects requires to set the watcher to compare object equality by setting the third watch parameter to true. Maybe you could add this to the docs? Cheers Ben
