### ISSUE TITLE
HTML5 validation support

### ISSUE THREAD

**Issue by sylouuu** [Toilal/ng-pickadate#23]
Hi,

Ok the custom angular validation works but it's not a common need.

The standard validation doesn't work, see http://plnkr.co/edit/59SMASmSGH9cQJPoo9Eq?p=preview

In case of `null`, you shouldn't trigger the form submit. The HTML5 validation must be called.

IMO, Same problem with `ng-required`.

Thanks

**Comment by Toilal** [comment]
Thanks for reporting. I'll do it, but I can't tell you when :)

**Comment by krugerdavid** [comment]
Hello @Toilal do you have any updates on this? Currently the same way you are showing on the readme isn't working for me either.

``` html
<form name="vm.tripForm" ng-submit="vm.searchTrip()" novalidate>
    <input id="departure" placeholder="Departure Date" name="departure_date" type="text" pick-a-date="vm.trip.date_departure" pick-a-date-options="vm.calOptions" min-date="vm.today" max-date="vm.trip.date_return">
    <div ng-messages="vm.tripForm.departure_date.$error" ng-if='vm.tripForm.$submitted || vm.tripForm.departure_date.$touched'>
        <div ng-message="required" class="error">Please select a date.</div>
    </div>
    <button type="submit">Submit</button>
</form>
```

**Comment by krugerdavid** [comment]
hi @Toilal were you able to take a look on the message?

**Comment by Toilal** [comment]
No sorry. I don't need this component anymore.
