### ISSUE TITLE
Way to specify default options

### ISSUE THREAD

**Issue by sylouuu** [Toilal/ng-pickadate#25]
Hi,

Could you create a provider in order to specify the default options instead of adding the same content in each `pick-a-date-options` attribute.

Something like:

``` js
app.config(function ($pickADateProvider) {
    $pickADateProvider.options({
        firstDay: 1,
        format: 'dd/mm/yyyy'
    });
});
```

Thanks!

**Comment by Toilal** [comment]
Good idea ! It will be in next version. (Don't ask me when, but it will :p)

**Comment by Toilal** [comment]
IT's there now.

**Comment by sylouuu** [comment]
Thx I'll try it.

Could you create a CHANGELOG.md or put the changelog in the release section?

Bests

**Comment by Toilal** [comment]
Sorry, I plan nothing better than this : https://github.com/Toilal/ng-pickadate/commits/master
