### ISSUE TITLE
Incorrect date when selecting 31st

### ISSUE THREAD

**Issue by carlpihl1** [Toilal/ng-pickadate#27]
The date is incorrectly set to the 1st in previous month, when selecting the 31st on previous month while the currently selected month only has 30 days.

Pull request with fix: https://github.com/Toilal/ng-pickadate/pull/28

**Comment by lagoasoft-lucasschmidt** [comment]
+1

I had this issue just today.

**Comment by Toilal** [comment]
Fixed and release, thanks !
