### ISSUE TITLE
`max` pickadate options

### ISSUE THREAD

**Issue by ardok** [Toilal/ng-pickadate#3]
Could you use the latest version of pickadate (3.5.5)?
It internally accepts `max` (I know you already have `max-date`, but this `max` would act in a different way).

https://github.com/amsul/pickadate.js/blob/master/CHANGELOG.md

**Comment by Toilal** [comment]
Thanks for the info, i'll do !

**Comment by ardok** [comment]
Oh, never mind.
I just realized `ng-pickadate` already sets the max and min through `max-date` and `min-date` after reading the code.
Hmm... oh well, sorry for the trouble!
