### ISSUE TITLE
What versions of angular are supported?

### ISSUE THREAD

**Issue by thoughtpalette** [Toilal/ng-pickadate#34]
Could you please add angular version support to the readme? I'm using 1.2.x and I'm having issues. (though it may not be related).

Great work!

**Comment by Toilal** [comment]
1.4.x is supported, as stated in bower.json. It should work with 1.3.x though. I didn't test with 1.2, it's possible it doesn't work ...

Maybe you could update [demo](https://github.com/Toilal/ng-pickadate/blob/master/demo/index.html) to check the behavior with angular 1.2.

**Comment by thoughtpalette** [comment]
Looks like `scope.$watchGroup` starts support in angular v.1.3.0
