### ISSUE TITLE
Run code after value is updated

### ISSUE THREAD

**Issue by ardok** [Toilal/ng-pickadate#4]
I'm still a newbie on Angular, but I can't seem to find a way to run a code after the value is set since `ng-pickadate` overrides the `onSet` callback.

So, I figured maybe I should use `$watch`. I tried something like:

```
// HTML
<input type="text" pick-a-date="startDate" placeholder="Select Start Date" max-date="endDate" pick-a-date-options="startPickerOptions" />

// Controller
var watchCb = function () { ... };
$scope.$watch('startDate', watchCb, true);
```

The problem is, `watchCb` is always get called first before the `updateValue` in `ng-pickadate`.

I know one thing that definitely works which is by doing this in `ng-pickadate` (starting line 15):

```
            var theOpt = scope.pickADateOptions || {};
            var options = angular.extend({}, theOpt, {
                onSet: function (e) {
                    ....
                    if (theOpt.onSet) {
                        theOpt.onSet(e);
                    }
                },
                onClose: function () {
                    element.blur();
                    if (theOpt.onClose) {
                        theOpt.onClose();
                    }
                }
            });
```

But there should be an easier way. Do you have any suggestion?

**Comment by Toilal** [comment]
In your own controller ...

``` js
$scope.$watch('startDate', function() {
    // Called when startDate change or scope initialize
});
```

This will also be called when the scope is initializing as you say, but you can check this by writing this.

``` js
$scope.$watch('startDate', function(newValue, oldValue) {
    if (newValue !== oldValue) {
        // Called when startDate change.
    }
});
```

At init time, `oldValue` can't be computed by angularJS, so it's set to the same value as `newValue`.

**Comment by rskuipers** [comment]
This doesn't actually work because we're working with the Date object. Why not implement an ng-change we can use?

**NOTE** Never mind, it works when using true as third parameter in watch like @ardok is using.

**Comment by francirp** [comment]
So putting this all together:

```
  $scope.$watch('startDate', function(newValue, oldValue) {
    if (newValue !== oldValue) {
      // on change action here
    }
  }, true);
```
