### ISSUE TITLE
Issue Regarding Dates

### ISSUE THREAD

**Issue by cfperea** [Toilal/ng-pickadate#5]
Hi, I just found this library and think is quite a good wrapper for pick-a-date, so congrats on the work!

However I found a small issue with the date algorithm which forces the date to be the wrong one when a certain date is picked. Let me explain.

I picked "February 14th, 2015" in the picker and the input field incorrectly showed "March 14th, 2015". When I looked at the code I noticed something:

```
scope.$apply(function () {
    if (e.hasOwnProperty('clear')) {
        scope.pickADate = null;
        return;
    }
    if (!scope.pickADate) {
        scope.pickADate = new Date(0);
    }
    scope.pickADate.setYear(select.obj.getFullYear());
    scope.pickADate.setMonth(select.obj.getMonth());
    scope.pickADate.setDate(select.obj.getDate());
});
```

In my case, `new Date(0)` returns _Wed Dec 31 1969 19:00:00 GMT-0500 (EST)_ so setting the year to 2015 moves the date to _Thu Dec 31 2015 19:00:00 GMT-0500 (EST)_. Up until this moment, everything seems to be working fine.

However, once the month is set to 1 (February) things don't go as expected as the date goes to _Tue Mar 03 2015 19:00:00 GMT-0500 (EST)_. This is because February only has 28 days in 2015 and since the day was kept on 31, the resulting date has to move 3 days ahead so it ends up on March 3rd, 2015. Finally when the day is set to 14, the month is already in March and therefore the date ends up being a full month ahead.

A solution could be to first set the year, then the day of the month, and finally the month. Another one would be to just force the day by calling `scope.pickADate.setMonth(select.obj.getMonth(), select.obj.getDate())`

I have applied the former solution in my local repository, however I would like to suggest you do the same.
This is my solution:

```
scope.$apply(function () {
    if (e.hasOwnProperty('clear')) {
        scope.pickADate = null;
        return;
    }
    if (!scope.pickADate) {
        scope.pickADate = new Date(0);
    }
    scope.pickADate.setYear(select.obj.getFullYear());
    scope.pickADate.setDate(select.obj.getDate());
    scope.pickADate.setMonth(select.obj.getMonth());
});
```

I have created a pull request for you if you feel like committing this change: https://github.com/Toilal/ng-pickadate/pull/6

Thanks and keep up the great work!

**Comment by Toilal** [comment]
Fixed in v0.1.6, thanks.
