### ISSUE TITLE
Clearing a pick-a-date does not reflect in it's model.

### ISSUE THREAD

**Issue by kumorig** [Toilal/ng-pickadate#9]
Thanks for the work you put in this!

 I have a problem with clearing a pick-a-date does not reflect in it's model. For example:
`<input type="text" pick-a-date="startDate" max-date="endDate"/>`
`<input type="text" pick-a-date="endDate" min-date="startDate"/>`

Setting values updates correctly, but pressing the clear button and the value remains in the model, 
as can be proved by outputting the value:

```
{{ startDate }} {{ endDate }}
```

This is particularly problematic using `max-date` and `min-date` since clearing a date will still limit the range on the other pick-a-date.

Also, I seem to be unable to set events functions as seen in the http://amsul.ca/pickadate.js/date/ options:

```
// Events
onStart: undefined,
onRender: undefined,
onOpen: undefined,
onClose: undefined,
onSet: undefined,
onStop: undefined,
```

**Comment by Toilal** [comment]
Could you open another issue for the second part ?

**Comment by kumorig** [comment]
Many thanks for fixing this!
